#Mounting the data:

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

#libs installation and importaion :

In [ ]:
!pip install joblib==1.1.0
!pip show joblib

Collecting joblib==1.1.0
  Downloading joblib-1.1.0-py2.py3-none-any.whl (306 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.0/307.0 kB 5.5 MB/s eta 0:00:00
Installing collected packages: joblib
  Attempting uninstall: joblib
    Found existing installation: joblib 1.3.1
    Uninstalling joblib-1.3.1:
      Successfully uninstalled joblib-1.3.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
imbalanced-learn 0.10.1 requires joblib>=1.1.1, but you have joblib 1.1.0 which is incompatible.
scikit-learn 1.2.2 requires joblib>=1.1.1, but you have joblib 1.1.0 which is incompatible.
Successfully installed joblib-1.1.0
Name: joblib
Version: 1.1.0
Summary: Lightweight pipelining with Python functions
Home-page: https://joblib.readthedocs.io
Author: Gael Varoquaux
Author-email: gael.varoquaux@normalesup.org
License: BSD
Location: /usr/local/lib/python3.10/dist-packages
Requires:
Required-by: imbalanced-learn, librosa, mlxtend, music21, nltk, scikit-learn

In [ ]:
import pandas as pd
from datetime import datetime
from pandas import read_csv
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OrdinalEncoder

In [ ]:

from calendar import day_abbr, month_abbr
import time
import itertools

from sklearn.preprocessing import LabelEncoder

from sklearn.model_selection import train_test_split
from imblearn.combine import SMOTEENN

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import GridSearchCV

from hyperopt import tpe
from hyperopt import STATUS_OK
from hyperopt import Trials
from hyperopt import hp
from hyperopt import fmin

from sklearn.utils.class_weight import compute_class_weight
from sklearn.linear_model import LogisticRegression

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import fbeta_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

#the LR model:

##the importing dataset :

In [ ]:
df =pd.read_csv('/content/gdrive/MyDrive/anomaly/2011-2012 Solar home electricity data v2.csv' )

In [ ]:
df.head(20)

,Customer,Generator Capacity,Postcode,Consumption Category,date,0:30,1:00,1:30,2:00,2:30,...,20:00,20:30,21:00,21:30,22:00,22:30,23:00,23:30,0:00,Row Quality
0,1,3.78,2076,CL,1/07/2011,1.250,1.250,1.250,0.625,0.219,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.063,NaN
1,1,3.78,2076,GC,1/07/2011,1.077,0.669,0.674,0.615,0.321,...,0.276,0.241,0.168,0.234,0.164,0.639,0.118,0.219,0.162,NaN
2,1,3.78,2076,GG,1/07/2011,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
3,1,3.78,2076,CL,2/07/2011,1.238,1.244,1.194,0.000,0.888,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.075,NaN
4,1,3.78,2076,GC,2/07/2011,0.476,0.130,0.044,0.094,0.032,...,0.234,0.306,0.183,0.240,0.170,0.506,0.224,0.088,0.084,NaN
5,1,3.78,2076,GG,2/07/2011,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
6,1,3.78,2076,CL,3/07/2011,1.238,1.244,1.250,1.256,1.050,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.081,NaN
7,1,3.78,2076,GC,3/07/2011,0.513,0.195,0.040,0.092,0.033,...,0.172,0.249,0.384,0.133,0.053,0.117,0.049,0.594,1.024,NaN
8,1,3.78,2076,GG,3/07/2011,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
9,1,3.78,2076,CL,4/07/2011,1.244,1.238,1.238,0.294,0.350,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.075,NaN
10,1,3.78,2076,GC,4/07/2011,1.158,0.731,0.603,0.633,0.578,...,0.294,0.232,0.183,0.370,0.244,0.887,1.082,1.035,0.613,NaN
11,1,3.78,2076,GG,4/07/2011,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
12,1,3.78,2076,CL,5/07/2011,1.244,1.250,1.244,0.681,0.519,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.075,NaN
13,1,3.78,2076,GC,5/07/2011,0.999,0.683,0.573,0.631,0.582,...,0.246,0.178,0.241,0.175,0.513,0.138,0.144,0.035,0.096,NaN
14,1,3.78,2076,GG,5/07/2011,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
15,1,3.78,2076,CL,6/07/2011,1.231,1.256,1.250,1.256,1.263,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.069,NaN
16,1,3.78,2076,GC,6/07/2011,0.463,0.118,0.088,0.742,1.046,...,0.293,0.256,0.282,0.463,0.366,0.071,0.146,0.040,0.106,NaN
17,1,3.78,2076,GG,6/07/2011,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,NaN
18,1,3.78,2076,CL,7/07/2011,1.238,1.250,1.250,1.263,1.250,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.088,NaN
19,1,3.78,2076,GC,7/07/2011,0.472,0.124,0.091,0.053,0.105,...,0.097,0.134,0.087,0.226,0.648,0.701,0.626,0.685,0.624,NaN

In [ ]:
df.shape

(270304, 54)

In [ ]:
df.var()

<ipython-input-9-28ded241fd7c>:1: FutureWarning: The default value of numeric_only in DataFrame.var is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.var()

Customer              7632.408829
Generator Capacity       1.046859
Postcode              7924.688902
0:30                     0.207045
1:00                     0.215376
1:30                     0.206045
2:00                     0.151063
2:30                     0.108160
3:00                     0.069694
3:30                     0.052061
4:00                     0.042767
4:30                     0.042166
5:00                     0.042323
5:30                     0.049711
6:00                     0.052517
6:30                     0.075570
7:00                     0.103222
7:30                     0.105832
8:00                     0.110827
8:30                     0.102652
9:00                     0.099811
9:30                     0.099874
10:00                    0.100516
10:30                    0.104424
11:00                    0.113066
11:30                    0.117320
12:00                    0.121144
12:30                    0.124062
13:00                    0.125514
13:30                    0.121317
14:00                    0.117688
14:30                    0.112830
15:00                    0.104410
15:30                    0.097576
16:00                    0.095327
16:30                    0.100317
17:00                    0.113475
17:30                    0.143945
18:00                    0.171433
18:30                    0.178269
19:00                    0.176378
19:30                    0.164915
20:00                    0.152167
20:30                    0.151633
21:00                    0.142269
21:30                    0.129756
22:00                    0.120897
22:30                    0.129636
23:00                    0.130141
23:30                    0.149144
0:00                     0.183660
Row Quality                   NaN
dtype: float64

## format the dataset :

In [ ]:



hourofday = []
minuteofhour = []
dayofweek = []
dayofmonth = []
monthofyear = []
year = []
consumption = []

# Loop through each row of the DataFrame
for index, row in df.iterrows():
    # Extract the date string and convert it to a datetime object
    date_str = row['date']
    dt = datetime.strptime(date_str, '%d/%m/%Y')


    # Loop through each time slot in the row and extract the required values
    for time_slot, cons in row.items():
        if time_slot in ['Customer', 'Generator Capacity', 'Postcode', 'Consumption Category', 'date', 'Row Quality']:
            continue  # Skip non-data columns

        # Extract the hour and minute values from the time slot string
        hour, minute = map(int, time_slot.split(':'))

        # Append the extracted values to their respective lists
        hourofday.append(hour)
        minuteofhour.append(minute)
        dayofweek.append(dt.weekday())
        dayofmonth.append(dt.day)
        monthofyear.append(dt.month)
        year.append(dt.year)
        consumption.append(float(cons))

# Create the output DataFrame with the extracted values
output_df = pd.DataFrame({
    'hourofday': hourofday,
    'minuteofhour': minuteofhour,
    'dayofweek': dayofweek,
    'dayofmonth': dayofmonth,
    'monthofyear': monthofyear,
    'year': year,
    'consumption': consumption
})

# Print the output DataFrame
print(output_df.head())

   hourofday  minuteofhour  dayofweek  dayofmonth  monthofyear  year  \
0          0            30          4           1            7  2011
1          1             0          4           1            7  2011
2          1            30          4           1            7  2011
3          2             0          4           1            7  2011
4          2            30          4           1            7  2011

   consumption
0        1.250
1        1.250
2        1.250
3        0.625
4        0.219

In [ ]:
output_df.shape[0]/df.shape[0]

48.0

In [ ]:
# Add metadata columns to the output DataFrame using the assign() method
output_df = output_df.assign(
    Customer=df['Customer'].repeat(48).values,
    Generator_Capacity=df['Generator Capacity'].repeat(48).values,
    Postcode=df['Postcode'].repeat(48).values,
    Consumption_Category=df['Consumption Category'].repeat(48).values,
    Row_Quality=df['Row Quality'].repeat(48).values
)

# Print the modified DataFrame
print(output_df.head())

   hourofday  minuteofhour  dayofweek  dayofmonth  monthofyear  year  \
0          0            30          4           1            7  2011
1          1             0          4           1            7  2011
2          1            30          4           1            7  2011
3          2             0          4           1            7  2011
4          2            30          4           1            7  2011

   consumption  Customer  Generator_Capacity  Postcode Consumption_Category  \
0        1.250         1                3.78      2076                   CL
1        1.250         1                3.78      2076                   CL
2        1.250         1                3.78      2076                   CL
3        0.625         1                3.78      2076                   CL
4        0.219         1                3.78      2076                   CL

   Row_Quality
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN

In [ ]:
output_df.iloc[47::48] #just for verify

,hourofday,minuteofhour,dayofweek,dayofmonth,monthofyear,year,consumption,Customer,Generator_Capacity,Postcode,Consumption_Category,Row_Quality
47,0,0,4,1,7,2011,1.063,1,3.78,2076,CL,NaN
95,0,0,4,1,7,2011,0.162,1,3.78,2076,GC,NaN
143,0,0,4,1,7,2011,0.000,1,3.78,2076,GG,NaN
191,0,0,5,2,7,2011,1.075,1,3.78,2076,CL,NaN
239,0,0,5,2,7,2011,0.084,1,3.78,2076,GC,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
12974399,0,0,4,29,6,2012,0.226,300,3.36,2086,GC,NaN
12974447,0,0,4,29,6,2012,0.000,300,3.36,2086,GG,NaN
12974495,0,0,5,30,6,2012,2.621,300,3.36,2086,CL,NaN
12974543,0,0,5,30,6,2012,0.235,300,3.36,2086,GC,NaN
12974591,0,0,5,30,6,2012,0.000,300,3.36,2086,GG,NaN

In [ ]:
Enc = OrdinalEncoder()
output_df["year"] = Enc.fit_transform(output_df[["year"]]).astype('int64')
output_df[["year"]].value_counts()

year
0       6526848
1       6447744
dtype: int64

In [ ]:
Enc_1 = OrdinalEncoder()
output_df["Customer"] = Enc_1.fit_transform(output_df[["Customer"]]).astype('int64')
output_df[["Customer"]].value_counts()

Customer
0           52704
167         52704
1           52704
153         52704
154         52704
            ...
174         35136
175         35136
176         35136
178         35136
197         35136
Length: 300, dtype: int64

In [ ]:
output_df.head()

,hourofday,minuteofhour,dayofweek,dayofmonth,monthofyear,year,consumption,Customer,Generator_Capacity,Postcode,Consumption_Category,Row_Quality
0,0,30,4,1,7,0,1.250,0,3.78,2076,CL,NaN
1,1,0,4,1,7,0,1.250,0,3.78,2076,CL,NaN
2,1,30,4,1,7,0,1.250,0,3.78,2076,CL,NaN
3,2,0,4,1,7,0,0.625,0,3.78,2076,CL,NaN
4,2,30,4,1,7,0,0.219,0,3.78,2076,CL,NaN

## add the anomaly column :

In [ ]:
# Group the data by customer and calculate the 90th percentile
q3 = output_df.groupby('Customer')['consumption'].quantile(0.9)

In [ ]:
q3

Customer
0      0.8280
1      0.5190
2      0.2880
3      0.2920
4      0.2630
        ...
295    0.3000
296    0.4090
297    0.3250
298    0.7965
299    0.9860
Name: consumption, Length: 300, dtype: float64

In [ ]:
# Define a function to set the anomaly flag
def set_anomaly(row):
    if row['consumption'] > q3[row['Customer']]:
        return 1
    else:
        return 0

# Apply the function to each row
output_df['anomaly'] = output_df.apply(set_anomaly, axis=1)

In [ ]:
# Count the number of occurrences of each value
counts = output_df['anomaly'].value_counts()

# Calculate the percentage of 1s and 0s
percentage_1 = counts[1] / len(output_df) * 100
percentage_0 = counts[0] / len(output_df) * 100
print(percentage_0,percentage_1)

90.04743270539836 9.952567294601632

In [ ]:
output_df.head(35)

,hourofday,minuteofhour,dayofweek,dayofmonth,monthofyear,year,consumption,Customer,Generator_Capacity,Postcode,Consumption_Category,Row_Quality,anomaly
0,0,30,4,1,7,0,1.250,0,3.78,2076,CL,NaN,1
1,1,0,4,1,7,0,1.250,0,3.78,2076,CL,NaN,1
2,1,30,4,1,7,0,1.250,0,3.78,2076,CL,NaN,1
3,2,0,4,1,7,0,0.625,0,3.78,2076,CL,NaN,0
4,2,30,4,1,7,0,0.219,0,3.78,2076,CL,NaN,0
5,3,0,4,1,7,0,1.013,0,3.78,2076,CL,NaN,1
6,3,30,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
7,4,0,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
8,4,30,4,1,7,0,0.125,0,3.78,2076,CL,NaN,0
9,5,0,4,1,7,0,0.894,0,3.78,2076,CL,NaN,1
10,5,30,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
11,6,0,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
12,6,30,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
13,7,0,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
14,7,30,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
15,8,0,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
16,8,30,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
17,9,0,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
18,9,30,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
19,10,0,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
20,10,30,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
21,11,0,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
22,11,30,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
23,12,0,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
24,12,30,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
25,13,0,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
26,13,30,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
27,14,0,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
28,14,30,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
29,15,0,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
30,15,30,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
31,16,0,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
32,16,30,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
33,17,0,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0
34,17,30,4,1,7,0,0.000,0,3.78,2076,CL,NaN,0

## add profil column :

In [ ]:
from sklearn.cluster import KMeans


# Step 1: Group customers by postcode and calculate mean consumption for each customer
customer_mean_consumption = output_df.groupby(['Postcode', 'Customer'])['consumption'].mean().reset_index()

# Step 2: Calculate the mean consumption for each group of customers with the same postcode
postcode_mean_consumption = customer_mean_consumption.groupby('Postcode')['consumption'].mean().reset_index()

# Step 3: Use K-means to cluster postcode groups into 3 profiles based on their mean consumption
kmeans = KMeans(n_clusters=3, random_state=42)
postcode_mean_consumption['Profile'] = kmeans.fit_predict(postcode_mean_consumption[['consumption']])

# Step 4: Map the profile labels back to each customer in the main DataFrame
output_df = output_df.merge(postcode_mean_consumption[['Postcode', 'Profile']], on='Postcode', how='left')

# Step 5: Rename the 'Profile' column to 'Profile_Label'
output_df.rename(columns={'Profile': 'Profile_Label'}, inplace=True)

# Display the updated DataFrame
print(output_df.head())

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(

   hourofday  minuteofhour  dayofweek  dayofmonth  monthofyear  year  \
0          0            30          4           1            7     0
1          1             0          4           1            7     0
2          1            30          4           1            7     0
3          2             0          4           1            7     0
4          2            30          4           1            7     0

   consumption  Customer  Generator_Capacity  Postcode Consumption_Category  \
0        1.250         0                3.78      2076                   CL
1        1.250         0                3.78      2076                   CL
2        1.250         0                3.78      2076                   CL
3        0.625         0                3.78      2076                   CL
4        0.219         0                3.78      2076                   CL

   Row_Quality  anomaly  Profile_Label
0          NaN        1              2
1          NaN        1              2
2          NaN        1              2
3          NaN        0              2
4          NaN        0              2

In [ ]:
result_df = output_df.drop_duplicates(subset=['Customer'])[['Customer', 'Profile_Label']]
print(result_df.head(25))

         Customer  Profile_Label
0               0              2
52704           1              1
105408          2              1
158112          3              1
210816          4              1
263520          5              1
316224          6              1
368928          7              2
421632          8              1
474336          9              1
527040         10              0
562176         11              0
597312         12              1
632448         13              1
685152         14              1
737856         15              0
772992         16              0
808128         17              0
860832         18              1
913536         19              1
948672         20              2
983808         21              1
1018944        22              1
1071648        23              0
1106784        24              0

# training phase :

##prepare the the features for the training :

In [ ]:
output_df.head()

,hourofday,minuteofhour,dayofweek,dayofmonth,monthofyear,year,consumption,Customer,anomaly,Profile_Label
0,0,30,4,1,7,0,1.250,0,1,2
1,1,0,4,1,7,0,1.250,0,1,2
2,1,30,4,1,7,0,1.250,0,1,2
3,2,0,4,1,7,0,0.625,0,0,2
4,2,30,4,1,7,0,0.219,0,0,2

In [ ]:
# Remove the columns
output_df = output_df.drop(['Generator_Capacity', 'Postcode', 'Consumption_Category', 'Row_Quality'], axis=1)

KeyError: ignored

##split the data :

In [ ]:
from sklearn.model_selection import train_test_split
#data spliting
# Create a boolean mask that is True for all columns except 'anomaly'
mask = output_df.columns != 'anomaly'

# Select the columns using the boolean mask
x = output_df.loc[:, mask]
y = output_df['anomaly']

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=4, stratify=y)

In [ ]:
y_train.value_counts()

0    9346629
1    1033044
Name: anomaly, dtype: int64

In [ ]:
y_train.values

array([1, 0, 0, ..., 0, 1, 0])

In [ ]:
output_df.tail(10)

,hourofday,minuteofhour,dayofweek,dayofmonth,monthofyear,year,consumption,Customer,anomaly,Profile_Label
12974582,19,30,5,30,6,1,0.0,299,0,0
12974583,20,0,5,30,6,1,0.0,299,0,0
12974584,20,30,5,30,6,1,0.0,299,0,0
12974585,21,0,5,30,6,1,0.0,299,0,0
12974586,21,30,5,30,6,1,0.0,299,0,0
12974587,22,0,5,30,6,1,0.0,299,0,0
12974588,22,30,5,30,6,1,0.0,299,0,0
12974589,23,0,5,30,6,1,0.0,299,0,0
12974590,23,30,5,30,6,1,0.0,299,0,0
12974591,0,0,5,30,6,1,0.0,299,0,0

##Train :

In [ ]:
def evaluation(y_true,y_pred,y_pred_proba):

    con_matrix = confusion_matrix(y_true, y_pred)
    tn,fp,fn,tp =con_matrix.flat

    classes=[0,1]
    fig, ax = plt.subplots()
    sns.heatmap(pd.DataFrame(con_matrix), annot=True,fmt='g', cmap="Blues")
    ticks = np.arange(len(classes))
    plt.xticks(ticks, classes)
    plt.yticks(ticks, classes)
    plt.title('Confusion matrix')
    plt.ylabel('True labels')
    plt.xlabel('Predicted labels')

#==================================================================
    Sensitivity = round(tp/(tp+fn),3)
    Specificity = round(tn/(tn+fp),3)
    G_mean=round(np.sqrt(Sensitivity*Specificity),3)
    print("\nSensitivity = Recall", Sensitivity,"\nSpecificity ",Specificity,"\nG_mean ",G_mean)

    fp_rate = round(fp/(fp+tn),3)
    print("\n False positive rate", fp_rate )
    print("\n True positive Rate ",Sensitivity)
    F2 = round(fbeta_score(y_true, y_pred, average='binary', beta=2),3)
    print("\n F2-score",F2)
      #===================================================================

    print("\n\n\n The classification_report")
    print(classification_report(y_true,y_pred, labels=[0,1]))

    #==================================================================

    P =round(precision_score(y_true, y_pred, average='weighted'),3)
    R = round(recall_score(y_true, y_pred, average='weighted'),3)
    F1 = round(f1_score(y_true, y_pred, average='weighted'),3)
    roc_auc = []
    if (np.array_equal(y_pred_proba,np.array([]))) != True:
        print("\n ROC curve + AUC score")
        fpr, tpr, _ = roc_curve(y_true, y_pred_proba)
        roc_auc = round(roc_auc_score(y_true, y_pred_proba),3)
        plt.plot(fpr,tpr,label="AUC="+str(roc_auc),marker='.')
        plt.xlabel('FPR')
        plt.ylabel('TPR')
        plt.legend()
        plt.show()

    #===================================================================

    scores=dict()
    scores['Sensitivity']=Sensitivity
    scores['Specificity']=Specificity
    scores['G_mean']=G_mean
    scores['False_positive_rate']=fp_rate
    scores['Precision']=P
    scores['Recall']=R
    scores['F1-score']=F1
    scores['F2-score']=F2
    scores['roc_auc_score']=roc_auc

    return scores

In [ ]:
#Logistic regression
#Calculate the weighing because we are faced an imbalanced
class_weight = compute_class_weight(class_weight='balanced',
                                    classes=np.unique(y_train),
                                    y=y_train)

In [ ]:
print(class_weight)

[0.55526292 5.02382909]

In [ ]:
%whos

Variable                    Type                Data/Info
---------------------------------------------------------
Enc                         OrdinalEncoder      OrdinalEncoder()
Enc_1                       OrdinalEncoder      OrdinalEncoder()
GridSearchCV                ABCMeta             <class 'sklearn.model_sel<...>on._search.GridSearchCV'>
KMeans                      ABCMeta             <class 'sklearn.cluster._kmeans.KMeans'>
LabelEncoder                type                <class 'sklearn.preproces<...>ing._label.LabelEncoder'>
LogisticRegression          type                <class 'sklearn.linear_mo<...>stic.LogisticRegression'>
OrdinalEncoder              type                <class 'sklearn.preproces<...>encoders.OrdinalEncoder'>
Pipeline                    ABCMeta             <class 'sklearn.pipeline.Pipeline'>
RepeatedStratifiedKFold     ABCMeta             <class 'sklearn.model_sel<...>RepeatedStratifiedKFold'>
SMOTEENN                    ABCMeta             <class 'imblearn.combine._smote_enn.SMOTEENN'>
STATUS_OK                   str                 ok
StandardScaler              type                <class 'sklearn.preproces<...>ng._data.StandardScaler'>
Trials                      type                <class 'hyperopt.base.Trials'>
class_weight                ndarray             2: 2 elems, type `float64`, 16 bytes
classification_report       function            <function classification_<...>report at 0x77ffb5adcb80>
compute_class_weight        function            <function compute_class_weight at 0x77ffb5fa3a30>
confusion_matrix            function            <function confusion_matrix at 0x77ffb5adc160>
cons                        float               nan
consumption                 list                n=12974592
counts                      Series              0    11683287\n1     1291<...>me: anomaly, dtype: int64
cross_val_score             function            <function cross_val_score at 0x77ffb57f3d90>
customer_mean_consumption   DataFrame                Postcode  Customer  <...>n\n[300 rows x 3 columns]
date_str                    str                 30/06/2012
datetime                    type                <class 'datetime.datetime'>
day_abbr                    _localized_day      <calendar._localized_day <...>object at 0x780003d2a110>
dayofmonth                  list                n=12974592
dayofweek                   list                n=12974592
df                          DataFrame                   Customer  Generat<...>270304 rows x 54 columns]
drive                       module              <module 'google.colab.dri<...>s/google/colab/drive.py'>
dt                          datetime            2012-06-30 00:00:00
evaluation                  function            <function evaluation at 0x77fe066b3250>
f1_score                    function            <function f1_score at 0x77ffb5adc5e0>
fbeta_score                 function            <function fbeta_score at 0x77ffb5adc670>
fmin                        function            <function fmin at 0x77ffb40cd7e0>
hour                        int                 0
hourofday                   list                n=12974592
hp                          module              <module 'hyperopt.hp' fro<...>packages/hyperopt/hp.py'>
index                       int                 270303
itertools                   module              <module 'itertools' (built-in)>
kmeans                      KMeans              KMeans(n_clusters=3, random_state=42)
mask                        ndarray             10: 10 elems, type `bool`, 10 bytes
minute                      int                 0
minuteofhour                list                n=12974592
month_abbr                  _localized_month    <calendar._localized_mont<...>object at 0x780003d2a1d0>
monthofyear                 list                n=12974592
np                          module              <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
output_df                   DataFrame                     hourofday  minu<...>974592 rows x 10 columns]
pd                          module              <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
percentage_0                float64             90.04743270539836
percentage_1                float64             9.952567294601632
plt                         module              <module 'matplotlib.pyplo<...>es/matplotlib/pyplot.py'>
postcode_mean_consumption   DataFrame               Postcode  consumption<...>n\n[100 rows x 3 columns]
precision_score             function            <function precision_score at 0x77ffb5adc9d0>
q3                          Series              Customer\n0      0.8280\n<...>ngth: 300, dtype: float64
read_csv                    function            <function read_csv at 0x77ffbd979cf0>
recall_score                function            <function recall_score at 0x77ffb5adca60>
result_df                   DataFrame                     Customer  Profi<...>n\n[300 rows x 2 columns]
roc_auc_score               function            <function roc_auc_score at 0x77ffb5abadd0>
roc_curve                   function            <function roc_curve at 0x77ffb5abb010>
row                         Series              Customer                 <...>me: 270303, dtype: object
set_anomaly                 function            <function set_anomaly at 0x77ffb40331c0>
sns                         module              <module 'seaborn' from '/<...>ges/seaborn/__init__.py'>
time                        module              <module 'time' (built-in)>
time_slot                   str                 Row Quality
tpe                         module              <module 'hyperopt.tpe' fr<...>ackages/hyperopt/tpe.py'>
train_test_split            function            <function train_test_split at 0x77ffb5ab9630>
x                           DataFrame                     hourofday  minu<...>2974592 rows x 9 columns]
x_test                      DataFrame                     hourofday  minu<...>2594919 rows x 9 columns]
x_train                     DataFrame                     hourofday  minu<...>0379673 rows x 9 columns]
y                           Series              0           1\n1         <...>h: 12974592, dtype: int64
y_test                      Series              5167323     1\n8454654   <...>th: 2594919, dtype: int64
y_train                     Series              9900518     1\n11024136  <...>h: 10379673, dtype: int64
year                        list                n=12974592

In [ ]:
del result_df,kmeans , customer_mean_consumption ,postcode_mean_consumption,counts
del df,output_df, Enc ,Enc_1
del hourofday ,minuteofhour,dayofweek ,dayofmonth ,monthofyear ,year ,consumption ,percentage_0, percentage_1

In [ ]:
start = time.time()
model_1 = LogisticRegression(class_weight='balanced',max_iter=5000)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

metric_F1 = cross_val_score(model_1, x_train, y_train, scoring='f1', cv=cv)
print('Mean F1_score: %.3f' % np.mean(metric_F1) )
metric_precision = cross_val_score(model_1, x_train, y_train, scoring='precision', cv=cv)
print ('Mean precision: %.3f'%np.mean(metric_precision))
metric_recall = cross_val_score(model_1, x_train, y_train, scoring='recall', cv=cv)
print ('Mean Recall: %.3f'%np.mean(metric_recall))
metric_accuracy = cross_val_score(model_1, x_train, y_train, scoring='accuracy', cv=cv)
print ('Mean accuracy: %.3f'%np.mean(metric_accuracy))
print("Logistic Regression with original data is done in %0.2fs" % (time.time() - start))

KeyboardInterrupt: ignored

In [ ]:
start = time.time()
model_2 = LogisticRegression( class_weight='balanced',max_iter=5000)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
scale = StandardScaler()
pipeline_1 = Pipeline(steps=[('scale', scale), ('model', model_2)])

metric_F1 = cross_val_score(pipeline_1, x_train, y_train, scoring='f1', cv=cv)
print('Mean F1_score: %.3f' % np.mean(metric_F1))

metric_precision = cross_val_score(model_1, x_train, y_train, scoring='precision', cv=cv)
print ('Mean precision: %.3f'%np.mean(metric_precision))
metric_recall = cross_val_score(model_1, x_train, y_train, scoring='recall', cv=cv)
print ('Mean Recall: %.3f'%np.mean(metric_recall))
metric_accuracy = cross_val_score(model_1, x_train, y_train, scoring='accuracy', cv=cv)
print ('Mean accuracy: %.3f'%np.mean(metric_accuracy))
print("Logistic Regression with resmapling and rescaling method is done in %0.2fs" % (time.time() - start))

In [ ]:
#Hyperparameter Tuning for LogisticRegression
#The main hyperparameters we will tune in logistic regression are solver, penalty,
#max_iter, C (regularization strength), tol, fit_intercept, intercept_scaling, class_weight, random_state, multi_class, verbose, warm_start, and l1_ratio
start = time.time()
LR_model = LogisticRegression(max_iter=5000,multi_class='ovr',verbose=True)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=0)
balance = [{0:10,1:1}, {0:1,1:1}, {0:1,1:10},'balanced']
param_grid = dict(model__class_weight=balance)
param_grid['model__C'] = [0.01, 0.1, 1, 10]
param_grid['model__solver'] = ['lbfgs', 'liblinear','saga']
param_grid['model__penalty'] = ['l1', 'l2']
scaling =StandardScaler()
pipe = Pipeline(steps=[('scaler', scaling), ('model', LR_model)])
search = GridSearchCV(pipe, param_grid ,scoring='f1', cv=cv)
best_model = search.fit(x_train, y_train)
end = time.time()

print('Best F1-Score: %s' % best_model.best_score_)
print('Best Hyperparameters: %s' % 0.923)
print('Time consumed is: ',end - start)

In [ ]:
best_model.best_score_

In [ ]:
best_model.best_params_

In [ ]:
scale = StandardScaler()
scale_resample_x=scale.fit_transform(x_train)
scale_resample_x=scale.transform(x_train)
scale_x_test= scale.transform(x_test)

start =time.time()
LR_model = LogisticRegression(class_weight={0: 1, 1: 1},C=0.01,solver='saga',penalty='l1',max_iter=5000
                              ,multi_class='ovr').fit(scale_resample_x, y_train)
y_pred =LR_model.predict(scale_x_test)
y_pred_proba=LR_model.predict_proba(scale_x_test)[::,1]
LR_run_time = time.time() - start
print("done in %0.3fs" % LR_run_time)

In [ ]:
LR_scores = evaluation(y_test,y_pred,y_pred_proba)

In [ ]:
import joblib

# Replace '/content/drive/MyDrive/' with the desired path in your Google Drive
save_path = 'logistic_regression_model.pkl'

# Save the trained model to a file
joblib.dump(LR_model, save_path)

In [ ]:
#import joblib
import numpy as np

# Load the trained model
model = joblib.load('logistic_regression_model.pkl')

# My train data is: costumer, GC, hourofday, minuteofhour, dayofweek, dayofmonth, monthofyear, year, Anomaly
# So to predict the anomaly, I use this dataEntry to test the model

dataEntry = np.array([[ 9, 0.071, 23, 30, 6, 30, 6, 2]])  # Reshape the input to a 2D array
prediction = model.predict(dataEntry)
print(prediction)